INSERT INTO MOVIE_LISTENER("ID", "NAME", "ACTORS") VALUES (1, 'The Matrix', 'Keanu Reeves, Laurence Fishburne, Carrie-Ann Moss')
INSERT INTO MOVIE_LISTENER("ID", "NAME", "ACTORS") VALUES (2, 'The Lord of The Rings', 'Elijah Wood, Ian Mckellen, Viggo Mortensen')
INSERT INTO MOVIE_LISTENER("ID", "NAME", "ACTORS") VALUES (3, 'Inception', 'Leonardo DiCaprio')
INSERT INTO MOVIE_LISTENER("ID", "NAME", "ACTORS") VALUES (4, 'The Shining', 'Jack Nicholson, Shelley Duvall')
INSERT INTO MOVIE_RATINGS("ID", "NAME", "RATING") VALUES (1, 'The Matrix', 60)
INSERT INTO MOVIE_RATINGS("ID", "NAME", "RATING") VALUES (2, 'The Lord of The Rings', 70)
INSERT INTO MOVIE_RATINGS("ID", "NAME", "RATING") VALUES (3, 'Inception', 80)
INSERT INTO MOVIE_RATINGS("ID", "NAME", "RATING") VALUES (4, 'The Shining', 90)