CREATE TABLE MOVIE_ENTITY_GRAPH("ID" INTEGER not null primary key, "NAME" VARCHAR(50))
CREATE TABLE MOVIE_ACTORS_ENTITY_GRAPH("ID" INTEGER not null primary key, "ACTOR1" VARCHAR(50) not null, "ACTOR2" VARCHAR(200))
ALTER TABLE MOVIE_ACTORS_ENTITY_GRAPH ADD CONSTRAINT MOVIE_ACTORS_GRAPH_FK FOREIGN KEY ("ID") REFERENCES MOVIE_ENTITY_GRAPH ("ID")