CREATE PROCEDURE DROP_TABLE(IN schemaName varchar(128), IN tableName varchar(128)) PARAMETER STYLE JAVA MODIFIES SQL DATA LANGUAGE JAVA EXTERNAL NAME 'org.jboss.arquillian.integration.persistence.datasource.derby.DerbyDropTable.dropTable'
CALL DROP_TABLE('app', 'SEQUENCE')
DROP PROCEDURE DROP_TABLE
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 10)
